"""Accent, interaction, and component tokens for Telegram Android."""

from __future__ import annotations

ACCENT_KEYS: tuple[str, ...] = (
    "PreviewBack",
    "PreviewBackLinear",
    "actionBarDefaultIcon",
    "actionBarDefaultSearch",
    "actionBarWhiteSelector",
    "avatar_backgroundBlueShadow",
    "avatar_backgroundCyanShadow",
    "avatar_backgroundGreenShadow",
    "avatar_backgroundOrangeShadow",
    "avatar_backgroundRedShadow",
    "avatar_backgroundVioletShadow",
    "changephoneinfo_image",
    "chat_attachAudioBackground",
    "chat_attachCameraIcon1",
    "chat_attachCameraIcon2",
    "chat_attachCameraIcon3",
    "chat_attachCameraIcon4",
    "chat_attachCameraIcon5",
    "chat_attachCameraIcon6",
    "chat_attachContactBackground",
    "chat_attachFileBackground",
    "chat_attachGalleryBackground",
    "chat_attachHideBackground",
    "chat_attachLocationBackground",
    "chat_attachMediaBanBackground",
    "chat_attachSendBackground",
    "chat_attachVideoBackground",
    "chat_botKeyboardButtonBackgroundPressed",
    "chat_botSwitchToInlineText",
    "chat_emojiPanelIcon",
    "chat_emojiPanelMasksIcon",
    "chat_emojiPanelMasksIconSelected",
    "chat_emojiPanelStickerSetName",
    "chat_inAudioSeekbar",
    "chat_inAudioSeekbarSelected",
    "chat_inBubbleShadow",
    "chat_inLoaderSelected",
    "chat_inVenueInfoSelectedText",
    "chat_inVenueInfoText",
    "chat_inVenueNameText",
    "chat_inVoiceSeekbar",
    "chat_inVoiceSeekbarSelected",
    "chat_outAudioSeekbar",
    "chat_outAudioSeekbarSelected",
    "chat_outBubbleShadow",
    "chat_outLoaderSelected",
    "chat_outVenueInfoSelectedText",
    "chat_outVenueInfoText",
    "chat_outVenueNameText",
    "chat_outVoiceSeekbar",
    "chat_outVoiceSeekbarSelected",
    "chat_recordedVoicePlayPausePressed",
    "chat_recordedVoiceProgress",
    "chats_actionBackground",
    "chats_unreadCounterMuted",
    "checkbox",
    "checkboxSquareDisabled",
    "contextProgressInner1",
    "dialogBadgeBackground",
    "dialogLineProgressBackground",
    "dialogSearchHint",
    "dialogSearchIcon",
    "dialogShadowLine",
    "emptyListPlaceholder",
    "fastScrollInactive",
    "featuredStickers_addButton",
    "featuredStickers_addedIcon",
    "files_folderIcon",
    "location_liveLocationProgress",
    "location_placeLocationBackground",
    "location_sendLiveLocationBackground",
    "location_sendLocationBackground",
    "musicPicker_buttonIcon",
    "musicPicker_checkbox",
    "picker_disabledButton",
    "player_buttonActive",
    "player_progressBackground",
    "profile_adminIcon",
    "sessions_devicesImage",
    "switch2Thumb",
    "switch2ThumbChecked",
    "switch2TrackChecked",
    "switchTrackChecked",
    "windowBackgroundWhiteBlueText6",
    "windowBackgroundWhiteBlueText7",
    "windowBackgroundWhiteValueText",
)

ACCENT_ALT_KEYS: tuple[str, ...] = (
    "chat_messageLinkIn",
    "chat_messageLinkOut",
    "chats_actionPressedBackground",
    "featuredStickers_addButtonPressed",
    "windowBackgroundWhiteLinkText",
)

CONTRAST_TEXT_KEYS: tuple[str, ...] = (
    "chat_inAudioDurationSelectedText",
    "chat_inAudioDurationText",
    "chat_inAudioPerfomerSelectedText",
    "chat_inAudioPerfomerText",
    "chat_inAudioPerformerSelectedText",
    "chat_inAudioSeekbarFill",
    "chat_inAudioTitleText",
    "chat_inContactBackground",
    "chat_inContactNameText",
    "chat_inContactPhoneText",
    "chat_inFileIcon",
    "chat_inFileInfoSelectedText",
    "chat_inFileInfoText",
    "chat_inFileNameText",
    "chat_inFileSelectedIcon",
    "chat_inForwardedNameText",
    "chat_inInstant",
    "chat_inInstantSelected",
    "chat_inLoader",
    "chat_inLoaderPhotoIcon",
    "chat_inLoaderPhotoIconSelected",
    "chat_inMenu",
    "chat_inMenuSelected",
    "chat_inPreviewInstantSelectedText",
    "chat_inPreviewInstantText",
    "chat_inPreviewLine",
    "chat_inReplyLine",
    "chat_inReplyMediaMessageSelectedText",
    "chat_inReplyMediaMessageText",
    "chat_inReplyMessageText",
    "chat_inReplyNameText",
    "chat_inSentClock",
    "chat_inSentClockSelected",
    "chat_inSiteNameText",
    "chat_inTimeSelectedText",
    "chat_inTimeText",
    "chat_inViaBotNameText",
    "chat_inViews",
    "chat_inViewsSelected",
    "chat_inVoiceSeekbarFill",
    "chat_inlineResultIcon",
    "chat_mediaTimeText",
    "chat_messageTextIn",
    "chat_messageTextOut",
    "chat_outAudioDurationSelectedText",
    "chat_outAudioDurationText",
    "chat_outAudioPerfomerText",
    "chat_outAudioPerformerSelectedText",
    "chat_outAudioSeekbarFill",
    "chat_outAudioTitleText",
    "chat_outContactBackground",
    "chat_outContactNameText",
    "chat_outContactPhoneText",
    "chat_outFileIcon",
    "chat_outFileInfoSelectedText",
    "chat_outFileInfoText",
    "chat_outFileNameText",
    "chat_outFileSelectedIcon",
    "chat_outForwardedNameText",
    "chat_outInstant",
    "chat_outInstantSelected",
    "chat_outLoader",
    "chat_outLoaderPhotoIcon",
    "chat_outLoaderPhotoIconSelected",
    "chat_outMenu",
    "chat_outMenuSelected",
    "chat_outPreviewInstantSelectedText",
    "chat_outPreviewInstantText",
    "chat_outPreviewLine",
    "chat_outReplyLine",
    "chat_outReplyMediaMessageSelectedText",
    "chat_outReplyMediaMessageText",
    "chat_outReplyMessageText",
    "chat_outReplyNameText",
    "chat_outSentCheck",
    "chat_outSentCheckSelected",
    "chat_outSentClock",
    "chat_outSentClockSelected",
    "chat_outSiteNameText",
    "chat_outTimeSelectedText",
    "chat_outTimeText",
    "chat_outViaBotNameText",
    "chat_outViews",
    "chat_outViewsSelected",
    "chat_outVoiceSeekbarFill",
    "chats_actionIcon",
    "checkboxCheck",
    "dialogBadgeText",
    "featuredStickers_buttonText",
)

TRANSPARENT_KEYS: tuple[str, ...] = (
    "switchThumb",
    "switchThumbChecked",
    "windowBackgroundGrayShadow",
)

ALPHA_SPECS: tuple[tuple[str, str, int], ...] = (
    ("actionBarActionModeDefaultSelector", "text_primary", 48),
    ("actionBarDefaultArchivedSelector", "text_primary", 48),
    ("actionBarDefaultSelector", "text_primary", 48),
    ("avatar_actionBarSelectorBlue", "text_primary", 48),
    ("avatar_actionBarSelectorCyan", "text_primary", 48),
    ("avatar_actionBarSelectorGreen", "text_primary", 48),
    ("avatar_actionBarSelectorOrange", "text_primary", 48),
    ("avatar_actionBarSelectorPink", "text_primary", 48),
    ("avatar_actionBarSelectorRed", "text_primary", 48),
    ("avatar_actionBarSelectorViolet", "text_primary", 48),
    ("avatar_backgroundGroupCreateSpanBlue", "text_primary", 180),
    ("chat_emojiPanelIconSelector", "text_primary", 48),
    ("chat_emojiPanelNewTrending", "text_primary", 0),
    ("chat_emojiPanelStickerPackSelector", "accent", 100),
    ("chat_linkSelectBackground", "text_primary", 50),
    ("chat_messagePanelVoiceShadow", "text_primary", 15),
    ("chat_secretTimerBackground", "text_primary", 204),
    ("chat_selectedBackground", "text_primary", 100),
    ("chat_serviceBackground", "surface", 180),
    ("chat_serviceBackgroundSelected", "surface", 180),
    ("chat_textSelectBackground", "text_primary", 100),
    ("chats_archivePinBackground", "text_primary", 200),
    ("chats_menuTopShadow", "surface", 100),
    ("dialogButtonSelector", "text_primary", 100),
    ("dialogLinkSelection", "text_primary", 50),
    ("dialogSearchBackground", "accent", 100),
    ("divider", "text_primary", 26),
    ("player_actionBarSelector", "text_primary", 48),
    ("stickers_menuSelector", "text_primary", 48),
    ("switch2Track", "accent", 75),
    ("switchTrack", "accent", 75),
    ("windowBackgroundWhiteLinkSelection", "accent", 50),
)
